### ISSUE TITLE
Fatal after installing Plesk but everything works fine

### ISSUE THREAD

**Issue by biofer76** [tzermias/ansible-plesk#2]
PLAY [Configure new Plesk server] **********************************************

TASK [setup] *******************************************************************
ok: [adc-plesk002.addictionlab.it]

TASK [ansible-plesk : Download Plesk installer] ********************************
ok: [adc-plesk002.addictionlab.it]

TASK [ansible-plesk : Run Plesk installer] *************************************
changed: [adc-plesk002.addictionlab.it]

TASK [ansible-plesk : Check whether Plesk has been configured] *****************
fatal: [adc-plesk002.addictionlab.it]: FAILED! => {"changed": true, "cmd": ["plesk", "bin", "init_conf", "--check-configured"], "delta": "0:00:06.974696", "end": "2016-03-21 10:29:44.362904", "failed": true, "rc": 1, "start": "2016-03-21 10:29:37.388208", "stderr": "\nexit status 1", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [ansible-plesk : Run Plesk initial configuration] *************************
changed: [adc-plesk002.addictionlab.it]

TASK [ansible-plesk : Disable poweruser mode] **********************************
changed: [adc-plesk002.addictionlab.it]

TASK [ansible-plesk : Install Plesk license (if specified)] ********************
skipping: [adc-plesk002.addictionlab.it]

PLAY RECAP *********************************************************************
adc-plesk002.addictionlab.it : ok=6    changed=3    unreachable=0    failed=0

**Comment by tzermias** [comment]
Hello @fabio-particles,

The task that fails is the "Check whether Plesk has been configured". It is added on purpose to ensure role idempotency. The task checks whether Plesk has already been configured (using the command `plesk sbin init_conf -c`) and if so, the initial configuration task is ignored. Try to run the role when Plesk has already been installed and configured, to see what happens.
If you need any more information or need a feature, feel free to ask!
