### ISSUE TITLE
specify single variables

### ISSUE THREAD

**Issue by davidak** [tzermias/ansible-plesk#3]
hello @tzermias,

we tried to specify a single variable in the host_vars like:

```
plesk.release_id: XXX
```

but it doesn't work. it still uses the default.

i think it was easier before your commit https://github.com/tzermias/ansible-plesk/commit/9b6161f8549347b5e80f2ea479e3b20e6bb4674a
What was the intention of that change?

**Comment by tzermias** [comment]
Hey @davidak,

Thank you for contacting me. `plesk` is a dictionary. This change was performed in order to have a better grouping on role variables. Try this instead in your host_vars and let me know:

```
plesk:
  release_id: XXX
```
